version: "3.8"
services:
  web:
    build: .
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle-volume:/usr/local/bundle
      - .history:/root/.bash_history
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  chrome:
    image: seleniarm/standalone-chromium:123.0
    platform: linux/x86_64
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    shm_size: '2gb'
    tty: true
volumes:
  bundle-volume:
  mysql-volume:
