version: "3.8"
services:
  web:
    build: .
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle-volume:/usr/local/bundle
      - .history:/root/.bash_history
    ports:
      - ${PORT:-3000}:3000
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  bundle-volume:
  mysql-volume:
